// package com.ftn.sbnz.rules.cep;

// import com.ftn.sbnz.model.events.PersonDetectionEvent;
// import com.ftn.sbnz.model.events.AggregatedDetection;

// rule "Aggregate 5 Minute Detection"
// when
//     $detection: PersonDetectionEvent($location: location, done == false)
//     $same: Number(intValue < 1) from accumulate(
//         $agg: AggregatedDetection(interval == "5m", location == $location) over window:time(4m),
//         count($agg)
//     )
//     $count: Number() from accumulate(
//         $event: PersonDetectionEvent(location == $location) over window:time(5m),
//         sum($event.numberOfPeople)
//     )
// then
//     AggregatedDetection aggregation = new AggregatedDetection($location, $count.intValue(), "5m");
//     insert(aggregation);
//     System.out.println("5 Minute Aggregation: " + aggregation.numberOfPeople);
// end;

// rule "No Person Detection in Last 5 Minutes"
// when
//     not (PersonDetectionEvent() over window:time(5m))
//     $detection: AggregatedDetection($location: location, interval == "5m", done == false)
//     $same: Number(intValue < 1) from accumulate(
//         $agg: AggregatedDetection(interval == "5m", location == $location, numberOfPeople == 0) over window:time(4m),
//         count($agg)
//     )
// then
//     AggregatedDetection aggregation = new AggregatedDetection($location, 0, "5m");
//     insert(aggregation);
//     System.out.println("5 Minute No Detection Aggregation: " + aggregation.numberOfPeople);
// end;

// rule "Aggregate 15 Minute Detection"
// when
//     $detection: AggregatedDetection($location: location, interval == "5m", done == false)
//     $same: Number(intValue < 1) from accumulate(
//         $agg: AggregatedDetection(interval == "15m", location == $location) over window:time(14m),
//         count($agg)
//     )
//     $count: Number(intValue % 3 == 0) from accumulate(
//         $agg: AggregatedDetection(interval == "5m", location == $location),
//         count($agg)
//     )
//     $aggregation: Number() from accumulate(
//         $agg: AggregatedDetection(interval == "5m", location == $location) over window:length(3),
//         sum($agg.numberOfPeople)
//     )
// then
//     AggregatedDetection aggregation = new AggregatedDetection($location, $aggregation.intValue(), "15m");
//     insert(aggregation);
//     System.out.println("15 Minute Aggregation: " + aggregation.numberOfPeople);
// end;

// rule "Aggregate 30 Minute Detection"
// when
//     $detection: AggregatedDetection($location: location, interval == "15m", done == false)
//     $same: Number(intValue < 1) from accumulate(
//         $agg: AggregatedDetection(interval == "30m", location == $location) over window:time(29m),
//         count($agg)
//     )
//     $count: Number(intValue % 2 == 0) from accumulate(
//         $agg: AggregatedDetection(interval == "15m", location == $location) over window:time(30m),
//         count($agg)
//     )
//     $aggregation: Number() from accumulate(
//         $agg: AggregatedDetection(interval == "15m", location == $location) over window:length(2),
//         sum($agg.numberOfPeople)
//     )
// then
//     AggregatedDetection aggregation = new AggregatedDetection($location, $aggregation.intValue(), "30m");
//     insert(aggregation);
//     System.out.println("30 Minute Aggregation: " + aggregation.numberOfPeople);
// end;

// rule "Aggregate 1 Hour Detection"
// when
//     $detection: AggregatedDetection($location: location, interval == "30m", done == false)
//     $same: Number(intValue < 1) from accumulate(
//         $agg: AggregatedDetection(interval == "1h", location == $location) over window:time(59m),
//         count($agg)
//     )
//     $count: Number(intValue % 2 == 0) from accumulate(
//         $agg: AggregatedDetection(interval == "30m", location == $location) over window:time(1h),
//         count($agg)
//     )
//     $aggregation: Number() from accumulate(
//         $agg: AggregatedDetection(interval == "30m", location == $location) over window:length(2),
//         sum($agg.numberOfPeople)
//     )
// then
//     AggregatedDetection aggregation = new AggregatedDetection($location, $aggregation.intValue(), "1h");
//     insert(aggregation);
//     System.out.println("1 Hour Aggregation: " + aggregation.numberOfPeople);
// end;

// rule "Aggregate 2 Hour Detection"
// when
//     $detection: AggregatedDetection($location: location, interval == "1h", done == false)
//     $same: Number(intValue < 1) from accumulate(
//         $agg: AggregatedDetection(interval == "2h", location == $location) over window:time(1h59m),
//         count($agg)
//     )
//     $count: Number(intValue % 2 == 0) from accumulate(
//         $agg: AggregatedDetection(interval == "1h", location == $location) over window:time(2h),
//         count($agg)
//     )
//     $aggregation: Number() from accumulate(
//         $agg: AggregatedDetection(interval == "1h", location == $location) over window:length(2),
//         sum($agg.numberOfPeople)
//     )
// then
//     AggregatedDetection aggregation = new AggregatedDetection($location, $aggregation.intValue(), "2h");
//     insert(aggregation);
//     System.out.println("2 Hour Aggregation: " + aggregation.numberOfPeople);
// end;

// rule "Aggregate 4 Hour Detection"
// when
//     $detection: AggregatedDetection($location: location, interval == "2h", done == false)
//     $same: Number(intValue < 1) from accumulate(
//         $agg: AggregatedDetection(interval == "4h", location == $location) over window:time(3h59m),
//         count($agg)
//     )
//     $count: Number(intValue % 2 == 0) from accumulate(
//         $agg: AggregatedDetection(interval == "2h", location == $location) over window:time(4h),
//         count($agg)
//     )
//     $aggregation: Number() from accumulate(
//         $agg: AggregatedDetection(interval == "2h", location == $location) over window:length(2),
//         sum($agg.numberOfPeople)
//     )
// then
//     AggregatedDetection aggregation = new AggregatedDetection($location, $aggregation.intValue(), "4h");
//     insert(aggregation);
//     System.out.println("4 Hour Aggregation: " + aggregation.numberOfPeople);
// end;

// rule "Aggregate 8 Hour Detection"
// when
//     $detection: AggregatedDetection($location: location, interval == "4h", done == false)
//     $same: Number(intValue < 1) from accumulate(
//         $agg: AggregatedDetection(interval == "8h", location == $location) over window:time(7h59m),
//         count($agg)
//     )
//     $count: Number(intValue % 2 == 0) from accumulate(
//         $agg: AggregatedDetection(interval == "4h", location == $location) over window:time(8h),
//         count($agg)
//     )
//     $aggregation: Number() from accumulate(
//         $agg: AggregatedDetection(interval == "4h", location == $location) over window:length(2),
//         sum($agg.numberOfPeople)
//     )
// then
//     AggregatedDetection aggregation = new AggregatedDetection($location, $aggregation.intValue(), "8h");
//     insert(aggregation);
//     System.out.println("8 Hour Aggregation: " + aggregation.numberOfPeople);
// end;

// rule "Aggregate 24 Hour Detection"
// when
//     $detection: AggregatedDetection($location: location, interval == "8h", done == false)
//     $same: Number(intValue < 1) from accumulate(
//         $agg: AggregatedDetection(interval == "24h", location == $location) over window:time(23h59m),
//         count($agg)
//     )
//     $count: Number(intValue % 2 == 0) from accumulate(
//         $agg: AggregatedDetection(interval == "8h", location == $location) over window:time(24h),
//         count($agg)
//     )
//     $aggregation: Number() from accumulate(
//         $agg: AggregatedDetection(interval == "8h", location == $location) over window:length(2),
//         sum($agg.numberOfPeople)
//     )
// then
//     AggregatedDetection aggregation = new AggregatedDetection($location, $aggregation.intValue(), "24h");
//     insert(aggregation);
//     System.out.println("24 Hour Aggregation: " + aggregation.numberOfPeople);
// end;
