package com.ftn.sbnz.rules.backward;

import com.ftn.sbnz.model.models.PeopleReportResult;
import com.ftn.sbnz.model.models.ReportFilter;

rule "Remove filters"
agenda-group "cleanup"
no-loop
    when
        $rf: ReportFilter()
    then
        delete($rf);
end;

rule "Remove reportResults"
agenda-group "cleanup"
no-loop
    when
        $prr: PeopleReportResult()
    then
        delete($prr);
end;