package com.ftn.sbnz.rules.backward_product;

import com.ftn.sbnz.model.models.ReportFilter;
import com.ftn.sbnz.model.models.ProductReportResult;

rule "Remove filters"
agenda-group "cleanup"
no-loop
    when
        $rf: ReportFilter()
    then
        delete($rf);
end;

rule "Remove reportResults"
agenda-group "cleanup"
no-loop
    when
        $prr: ProductReportResult()
    then
        delete($prr);
end;