name: sbnz
services:
  postgres_db:
    image: postgres:16.0-alpine3.18
    container_name: postgres_db
    volumes:
      - dev-rdb-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sbnz
      - POSTGRES_USER=sbnz
      - POSTGRES_PASSWORD=sbnz
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sbnz -d sbnz" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  dev-rdb-data:
  data:
